site_name: Python Retroactive Data Structures
site_description: 'Fun with time travel: implementing retroactive data structures in Python'

repo_url: http://github.com/csvoss/retroactive/tree/master/docs
repo_name: GitHub

site_author: Chelsea Voss, Massachusetts Institute of Technology

pages:
- ["index.md", Home]
- ["whatisretroactivity.md", "What is retroactivity?"]
- ["examples.md", "Examples"]

- ['general.md', "General Transformations"]
- ['specifics.md', "Specific Implementations"]
- ['basics.md', "Basic Building Blocks"]

- ["futuredevelopments.md", "Future Developments"]
- ["references.md", "References"]

theme: readthedocs
